// <auto-generated />
namespace UDG.Colloquium.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ManyToManyColloquims : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManyToManyColloquims));
        
        string IMigrationMetadata.Id
        {
            get { return "201409131755327_ManyToManyColloquims"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
