// <auto-generated />
namespace UDG.Colloquium.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ContactsInUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactsInUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201407010404214_ContactsInUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
