// <auto-generated />
namespace UDG.Colloquium.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedMoreValidations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedMoreValidations));
        
        string IMigrationMetadata.Id
        {
            get { return "201406181654123_Added More Validations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
