// <auto-generated />
namespace UDG.Colloquium.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddingRoleDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingRoleDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201501132317174_AddingRoleDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
